#!/usr/bin/env python
from __future__ import print_function

import os, fnmatch
from argparse import ArgumentParser

def shell(command):
    print(command)
    os.system(command)

def find_gyb_files( * filetypes ):
    for root, directories, files in os.walk('.'):
        for filetype in filetypes:
            for file in fnmatch.filter(files, '*.{0}.gyb'.format(filetype)):
                yield os.path.join(root, file)

def main():
    flags = {
        'cc': '-Xcc -I/usr/local/include', 
        'ld': '-Xlinker -L/usr/local/lib'
    }
    parser = ArgumentParser()
    parser.add_argument('-d', '--debug', action='store_true')
    parser.add_argument('-l', '--line-directive', action='store_true')
    parser.add_argument('--no-gyb', action='store_true')
    
    arguments = parser.parse_args()
    
    gyb_targets = [path[:-4] for path in find_gyb_files('swift')]
    
    if not arguments.no_gyb:
        for target in gyb_targets:
            shell('utils/swift/gyb {0}.gyb -o {0}'.format(target))
    
    if arguments.debug:
        command = 'swift build -c debug -Xswiftc "-D" -Xswiftc "DEBUG" {cc} {ld}'
    else:
        command = 'swift build -c release {cc} {ld}'
    
    command = command.format( ** flags )
    
    if arguments.line_directive:
        command = 'utils/swift/line-directive {0} -- {1}'.format(' '.join(gyb_targets), command)
    
    shell(command)
    
    if not arguments.no_gyb:
        shell('rm {0}'.format(' '.join(gyb_targets)))
    
if __name__ == '__main__':
    # set cwd
    location = os.path.dirname(__file__)
    os.chdir(os.path.join(location, '..'))
    main()
