#!/usr/bin/env python
from __future__ import print_function

import os, fnmatch
from argparse import ArgumentParser

def shell(command):
    print(command)
    os.system(command)

def find_gyb_directories():
    for root, directories, files in os.walk('sources/'):
        for directory in directories:
            if directory == '__gyb__':
                yield os.path.join(root, directory)

def main():
    shell('rm -rf {0}'.format(' '.join(find_gyb_directories())))
    shell('rm -rf .build/ Package.resolved')
    
if __name__ == '__main__':
    # set cwd
    location = os.path.dirname(__file__)
    os.chdir(os.path.join(location, '..'))
    main()
